### ISSUE TITLE
Test new database (AWS)

### ISSUE THREAD

**Issue by robperch** [robperch/IEOR_Capstone#27]
A database has been created to handle the data used in the project. The main tasks for this issue are:

- [x]  Check if you can connect to the database using the provided credentials.
- [x]  Create a test table named 'raw' and insert a small sample of the data (one week) that we are obtaining from the production database.
- [x] Create function to automate extracting data from the company database and saving it in the new database (careful not to upload any identifiable info from clients)

**Comment by martinhe07** [comment]
Wanna check in for this issue ticket. @robperch @jefwei Is it complete, and can we mark this issue as "Done"?

**Comment by robperch** [comment]
Yes, We can close this issue... the test database worked.
