### ISSUE TITLE
Create a centralized, shared Google Drive folder

### ISSUE THREAD

**Issue by martinhe07** [robperch/IEOR_Capstone#41]
Let's create a shared Google Drive folder where we save all our documents and files.

Here's the link to the shared folder I've created: https://drive.google.com/drive/folders/1oUfH6S7d3mG-OF47OcpViRiLHF9rHE4M

**Comment by martinhe07** [comment]
Hi @robperch - Could we move our Statement of Work document to this shared folder, since you are the owner of this document?
URL to Statement of Work: https://docs.google.com/document/d/1gwmfwoECE5gxJPm506RTUSm04E3hsgFtf3VxZ29JLac/edit

Once done, feel free to mark this issue as "Done".

**Comment by robperch** [comment]
Of course! I've moved the document to the folder. I'll close this issue.
